/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f103xx.h>
#include <gpiox_driver.h>
#include <timerx_driver.h>
#include <rcc_driver.h>
#include <ssd1306_i2c_driver.h>

void SysClock_Init(void);
void OLED_Init(void);
void I2C_INIT(void);

GPIO_Handle_t sda, scl;
RCC_Handle_t hRcc;
TIMER2_5_Handle_t Timer2;
I2C_Handle_t i2c1;
SSD1306_Handle_t oled;

int main(void) {
    SysClock_Init(); // 72 MHz
    I2C_INIT();
    OLED_Init();
//    Timer2 = TIMER2_5_Init_Delay(TIMER2, 719999);
//
    SSD1306_DrawPixel(&oled, 10, 10, 1);
    SSD1306_DrawPixel(&oled, 11, 11, 1);
    SSD1306_DrawPixel(&oled, 12, 12, 1);
    SSD1306_Update(&oled);

    for (;;) {
        // Có thể vẽ thêm, animation, hoặc kiểm tra trạng thái OLED
    }
}

void SysClock_Init(void) {
    hRcc.Config.clk_src = RCC_CLK_PLL;
    hRcc.Config.pll_src = RCC_PLL_SRC_HSE;
    hRcc.Config.pll_mul = RCC_PLL_MUL_9;
    hRcc.Config.ahb_prescaler = RCC_AHB_DIV_1;
    hRcc.Config.apb1_prescaler = RCC_APB_DIV_2;
    hRcc.Config.apb2_prescaler = RCC_APB_DIV_1;
    RCC_ConfigClock(&hRcc);

}
void I2C_INIT(void)
{
    sda = GPIO_Init(GPIOB, GPIO_PIN_7, GPIO_MODE_OUTPUT_10MHz, GPIO_CNF_AF_OD);
    scl = GPIO_Init(GPIOB, GPIO_PIN_6, GPIO_MODE_OUTPUT_10MHz, GPIO_CNF_AF_OD);

    i2c1 = I2C_Init(
        I2C1,
        100000,
        I2C_ADDRESSINGMODE_7BIT,
        0x00,
        I2C_ACK_ENABLE,
        I2C_DUTYCYCLE_2
    );
    I2C_ScanDevices(&i2c1);

}
void OLED_Init(void) {


    oled.Instance = &i2c1;
    oled.Config.Address = 0x3C;
    oled.Config.Width = 128;
    oled.Config.Height = 32;

    SSD1306_Init(&oled);
}


