/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f103xx.h>
#include <gpiox_driver.h>
#include <L9110_driver.h>
#include <rcc_driver.h>
#include "timer_advance_driver.h"

void SysClock_Init(void);
void l9110_Init(void);

GPIO_Handle_t  Digital,Pwm;
RCC_Handle_t hRcc;
L9110_Handle_t l9110;

TIMER_Advance_Handle_t htim1;

int main(void) {
	SysClock_Init();
	l9110_Init();
	L9110_Run(&l9110, L9110_DIRECTION_FORWARD, 35);

	for (;;) {
	}
}
void l9110_Init() {
	Pwm = GPIO_Init(GPIOA, GPIO_PIN_10, GPIO_MODE_OUTPUT_10MHz, GPIO_CNF_AF_PP);
	Digital = GPIO_Init(GPIOA, GPIO_PIN_12, GPIO_MODE_OUTPUT_10MHz, GPIO_CNF_OUTPUT_PP);

	htim1.Instance = TIMER1;   // Địa chỉ base của TIM1
	htim1.Config.Feature     = TIM1_FEATURE_PWM;
	htim1.Config.Prescaler   = 72 - 1;       // PSC = 71 => 1MHz tick (nếu fclk = 72MHz)
	htim1.Config.AutoReload  = 1000 - 1;     // ARR = 999 => 1kHz PWM
	htim1.Config.Channel     = TIM1_CHANNEL_3;
	htim1.Config.OCMode      = TIM1_OCMODE_PWM1;
	htim1.Config.CompareValue= 500;          // 50% duty
	TIMER_Advance_Init(&htim1);

	l9110.Pwm_Pin = &Pwm;
	l9110.Digital_Pin = &Digital;
	l9110.hTIM = &htim1;

}
void SysClock_Init(void) {
    hRcc.Config.clk_src = RCC_CLK_PLL;
    hRcc.Config.pll_src = RCC_PLL_SRC_HSE;
    hRcc.Config.pll_mul = RCC_PLL_MUL_9;
    hRcc.Config.ahb_prescaler = RCC_AHB_DIV_1;
    hRcc.Config.apb1_prescaler = RCC_APB_DIV_2;
    hRcc.Config.apb2_prescaler = RCC_APB_DIV_1;
    RCC_ConfigClock(&hRcc);

}



